// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBLXDpi-242BpLXv1yy1DfDEXSa8VKA2g',
    appId: '1:606301812782:web:a7dd42e33377f29b7b07bf',
    messagingSenderId: '606301812782',
    projectId: 'latihan-flutter-93e64',
    authDomain: 'latihan-flutter-93e64.firebaseapp.com',
    storageBucket: 'latihan-flutter-93e64.firebasestorage.app',
    measurementId: 'G-W1GJ117QM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR7f094Aat0XDbLpPFRNpK6KhqARPXU6w',
    appId: '1:606301812782:android:6d9a32b174a41b417b07bf',
    messagingSenderId: '606301812782',
    projectId: 'latihan-flutter-93e64',
    storageBucket: 'latihan-flutter-93e64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz9VZmoHnvqjVmOcyciK27d5-WEiHu5rw',
    appId: '1:606301812782:ios:71f731d0a5f8b73b7b07bf',
    messagingSenderId: '606301812782',
    projectId: 'latihan-flutter-93e64',
    storageBucket: 'latihan-flutter-93e64.firebasestorage.app',
    androidClientId: '606301812782-b6gonfe42k29098cm9ms9lr63015di2h.apps.googleusercontent.com',
    iosClientId: '606301812782-5fe4br44iu6vn0rgg3e5832ioc66p3ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz9VZmoHnvqjVmOcyciK27d5-WEiHu5rw',
    appId: '1:606301812782:ios:71f731d0a5f8b73b7b07bf',
    messagingSenderId: '606301812782',
    projectId: 'latihan-flutter-93e64',
    storageBucket: 'latihan-flutter-93e64.firebasestorage.app',
    androidClientId: '606301812782-b6gonfe42k29098cm9ms9lr63015di2h.apps.googleusercontent.com',
    iosClientId: '606301812782-5fe4br44iu6vn0rgg3e5832ioc66p3ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBLXDpi-242BpLXv1yy1DfDEXSa8VKA2g',
    appId: '1:606301812782:web:0f018cabaff0d9f17b07bf',
    messagingSenderId: '606301812782',
    projectId: 'latihan-flutter-93e64',
    authDomain: 'latihan-flutter-93e64.firebaseapp.com',
    storageBucket: 'latihan-flutter-93e64.firebasestorage.app',
    measurementId: 'G-RL96XRTMHV',
  );
}
